apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  labels:
    app: prometheus
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
  type: NodePort
  selector:
    app: prometheus
