apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
data:
  prom.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-svc:9090
        isDefault: true
        version: 1
        editable: false
