{
 "title": "C-Chain",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Accepted Blocks in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(avalanche_C_blks_accepted_count{job=\"avalanche\"}[1m]))>0",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Rejected Blocks in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(avalanche_C_blks_rejected_count{job=\"avalanche\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Average Block Acceptance Latency",
   "type": "timeseries",
   "description": "The average time between a block's issuance and acceptance by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_C_blks_accepted_sum{job=\"avalanche\"}[5m]) / rate(avalanche_C_blks_accepted_count{job=\"avalanche\"}[5m])",
     "legendFormat": "Avg Acceptance Latency"
    }
   ]
  },
  {
   "title": "Average Block Rejection Latency",
   "type": "timeseries",
   "description": "The average time between a block's issuance and rejection by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_C_blks_rejected_sum{job=\"avalanche\"}[5m]) / rate(avalanche_C_blks_rejected_count{job=\"avalanche\"}[5m])",
     "legendFormat": "Avg Rejection Latency"
    }
   ]
  },
  {
   "title": "Processing Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_C_blks_processing{job=\"avalanche\"}>0",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Incomplete Polls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "avalanche_C_polls > 0" }
   ]
  },
  {
   "title": "Message Handling Time (Total)",
   "type": "timeseries",
   "description": "Measures how much of each second is being spent handling different kinds of messages on the C-Chain.\nThe value for chits, for example, is the number of seconds spent handling chits messages per second, over the last 30 seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_C_handler_pull_query_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_C_handler_push_query_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_C_handler_chits_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_C_handler_accepted_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_C_handler_put_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_C_handler_multiput_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_C_handler_get_failed_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_C_handler_query_failed_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_C_handler_get_accepted_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_failed_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(avalanche_C_handler_app_request_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(avalanche_C_handler_app_request_failed_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(avalanche_C_handler_app_response_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "app response"
    },
    {
     "expr": "rate(avalanche_C_handler_app_gossip_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "app gossip"
    }
   ]
  },
  {
   "title": "Percentage of Successful Queries",
   "type": "timeseries",
   "description": "Percentage of queries for which we receive chits on time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(avalanche_C_handler_chits_count{job=\"avalanche\"}[5m]) + 1) / (increase(avalanche_C_handler_chits_count{job=\"avalanche\"}[5m]) + increase(avalanche_C_handler_query_failed_count{job=\"avalanche\"}[5m]) + 1)",
     "legendFormat": "% Successful"
    }
   ]
  },
  {
   "title": "Message Handling Time (per Message)",
   "type": "timeseries",
   "description": "Measures how long each kind of request on the C-Chain takes to handle.\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_C_handler_pull_query_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_pull_query_count{job=\"avalanche\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_C_handler_push_query_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_push_query_count{job=\"avalanche\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_C_handler_chits_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_chits_count{job=\"avalanche\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_C_handler_accepted_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_accepted_count{job=\"avalanche\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_get_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_C_handler_put_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_C_handler_multiput_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_multi_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_get_ancestors_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_C_handler_get_failed_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_get_failed_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_C_handler_query_failed_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_query_failed_count{job=\"avalanche\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_C_handler_get_accepted_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_get_accepted_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_failed_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_get_ancestors_failed_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(avalanche_C_handler_app_request_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_app_request_count{job=\"avalanche\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(avalanche_C_handler_app_request_failed_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_app_request_failed_count{job=\"avalanche\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(avalanche_C_handler_app_response_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_app_response_count{job=\"avalanche\"}[5m])",
     "legendFormat": "app response"
    },
    {
     "expr": "rate(avalanche_C_handler_app_gossip_sum{job=\"avalanche\"}[5m])/rate(avalanche_C_handler_app_gossip_count{job=\"avalanche\"}[5m])",
     "legendFormat": "app gossip"
    }
   ]
  },
  {
   "title": "AVAX Benched",
   "type": "timeseries",
   "description": "The total stake of validators currently \"benched\" due to poor query responsiveness. Queries to these validators will immediately timeout until they are removed from the \"bench.\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(avalanche_C_benchlist_benched_weight{job=\"avalanche\"}[15m]) / 10^9",
     "legendFormat": "AVAX Benched"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "timeseries",
   "description": "Measures how many of each kind of message are received per second on the C-Chain.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(avalanche_C_handler_pull_query_count{job=\"avalanche\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_C_handler_push_query_count{job=\"avalanche\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_C_handler_chits_count{job=\"avalanche\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_C_handler_accepted_count{job=\"avalanche\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_C_handler_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_C_handler_multi_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_C_handler_get_failed_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_C_handler_query_failed_count{job=\"avalanche\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_C_handler_get_accepted_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_failed_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(avalanche_C_handler_app_request_count{job=\"avalanche\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(avalanche_C_handler_app_request_failed_count{job=\"avalanche\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(avalanche_C_handler_app_response_count{job=\"avalanche\"}[5m])",
     "legendFormat": "app response"
    },
    {
     "expr": "rate(avalanche_C_handler_app_gossip_count{job=\"avalanche\"}[5m])",
     "legendFormat": "app gossip"
    }
   ]
  },
  {
   "title": "Block ID Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the cache where the key is the byte representation of the block, and the value is the block's ID",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(avalanche_C_vm_rpcchainvm_bytes_to_id_cache_hit[5m])/(increase(avalanche_C_vm_rpcchainvm_bytes_to_id_cache_hit[5m])+increase(avalanche_C_vm_rpcchainvm_bytes_to_id_cache_miss[5m]))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Missing Block Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the missing block cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "increase(avalanche_C_vm_rpcchainvm_missing_cache_hit[5m])/(increase(avalanche_C_vm_rpcchainvm_missing_cache_hit[5m])+increase(avalanche_C_vm_rpcchainvm_missing_cache_miss[5m]))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Decided Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the decided block cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "increase(avalanche_C_vm_rpcchainvm_decided_cache_hit[5m])/(increase(avalanche_C_vm_rpcchainvm_decided_cache_hit[5m])+increase(avalanche_C_vm_rpcchainvm_decided_cache_miss[5m]))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Unverified Block Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the unverified block cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "increase(avalanche_C_vm_rpcchainvm_unverified_cache_hit[5m])/(increase(avalanche_C_vm_rpcchainvm_unverified_cache_hit[5m])+increase(avalanche_C_vm_rpcchainvm_unverified_cache_miss[5m]))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Unprocessed Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_C_handler_unprocessed_msgs_len",
     "legendFormat": "Pending Messages"
    }
   ]
  },
  {
   "title": "Incoming Messages Expired in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(avalanche_C_handler_expired[1m])",
     "legendFormat": "Expired"
    }
   ]
  }
 ]
}
{
 "title": "Database",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Database Read Rate",
   "type": "timeseries",
   "description": "Database read rate. Note that these reads may be from caches and not from disk.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(avalanche_db_read_size_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "Bytes Read"
    }
   ]
  },
  {
   "title": "Database Write Rate",
   "type": "timeseries",
   "description": "Database write rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(avalanche_db_write_size_sum{job=\"avalanche\"}[5m])",
     "legendFormat": "Write Rate"
    }
   ]
  },
  {
   "title": "Total Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second across all chains",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(avalanche_db_count{job=\"avalanche\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_db_get_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_db_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(avalanche_db_has_count{job=\"avalanche\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(avalanche_db_compact_size_count{job=\"avalanche\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(avalanche_db_batch_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(avalanche_db_batch_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(avalanche_db_batch_reset_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(avalanche_db_batch_replay_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "Total Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_db_put_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(avalanche_db_get_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_get_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(avalanche_db_delete_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(avalanche_db_has_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_has_count{job=\"avalanche\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(avalanche_db_compact_size_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_compact_size_count{job=\"avalanche\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(avalanche_db_batch_put_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_batch_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(avalanche_db_batch_delete_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_batch_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(avalanche_db_batch_reset_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_batch_reset_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(avalanche_db_batch_replay_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_batch_replay_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "X-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second on X-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(avalanche_X_db_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_X_db_get_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_X_db_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(avalanche_X_db_has_count{job=\"avalanche\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(avalanche_X_db_compact_size_count{job=\"avalanche\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(avalanche_X_db_batch_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(avalanche_X_db_batch_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(avalanche_X_db_batch_reset_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(avalanche_X_db_batch_replay_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "X-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on X-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_X_db_put_sum{job=\"avalanche\"}[5m])/increase(avalanche_X_db_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(avalanche_X_db_get_sum{job=\"avalanche\"}[5m])/increase(avalanche_X_db_get_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(avalanche_X_db_delete_sum{job=\"avalanche\"}[5m])/increase(avalanche_X_db_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(avalanche_X_db_has_sum{job=\"avalanche\"}[5m])/increase(avalanche_X_db_has_count{job=\"avalanche\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(avalanche_X_db_compact_size_sum{job=\"avalanche\"}[5m])/increase(avalanche_X_db_compact_size_count{job=\"avalanche\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(avalanche_X_db_batch_put_sum{job=\"avalanche\"}[5m])/increase(avalanche_X_db_batch_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(avalanche_X_db_batch_delete_sum{job=\"avalanche\"}[5m])/increase(avalanche_X_db_batch_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(avalanche_X_db_batch_reset_sum{job=\"avalanche\"}[5m])/increase(avalanche_X_db_batch_reset_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(avalanche_X_db_batch_replay_sum{job=\"avalanche\"}[5m])/increase(avalanche_X_db_batch_replay_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "P-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second on P-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(avalanche_P_db_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_P_db_get_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_P_db_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(avalanche_P_db_has_count{job=\"avalanche\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(avalanche_P_db_compact_size_count{job=\"avalanche\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(avalanche_P_db_batch_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(avalanche_P_db_batch_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(avalanche_P_db_batch_reset_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(avalanche_P_db_batch_replay_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "P-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on P-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_P_db_put_sum{job=\"avalanche\"}[5m])/increase(avalanche_P_db_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(avalanche_P_db_get_sum{job=\"avalanche\"}[5m])/increase(avalanche_P_db_get_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(avalanche_P_db_delete_sum{job=\"avalanche\"}[5m])/increase(avalanche_P_db_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(avalanche_P_db_has_sum{job=\"avalanche\"}[5m])/increase(avalanche_P_db_has_count{job=\"avalanche\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(avalanche_P_db_compact_size_sum{job=\"avalanche\"}[5m])/increase(avalanche_P_db_compact_size_count{job=\"avalanche\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(avalanche_P_db_batch_put_sum{job=\"avalanche\"}[5m])/increase(avalanche_P_db_batch_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(avalanche_P_db_batch_delete_sum{job=\"avalanche\"}[5m])/increase(avalanche_P_db_batch_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(avalanche_P_db_batch_reset_sum{job=\"avalanche\"}[5m])/increase(avalanche_P_db_batch_reset_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(avalanche_P_db_batch_replay_sum{job=\"avalanche\"}[5m])/increase(avalanche_P_db_batch_replay_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "C-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second across all chains",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(avalanche_C_db_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_C_db_get_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_C_db_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(avalanche_C_db_has_count{job=\"avalanche\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(avalanche_C_db_compact_size_count{job=\"avalanche\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(avalanche_C_db_batch_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(avalanche_C_db_batch_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(avalanche_C_db_batch_reset_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(avalanche_C_db_batch_replay_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "C-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on C-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_C_db_put_sum{job=\"avalanche\"}[5m])/increase(avalanche_C_db_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(avalanche_C_db_get_sum{job=\"avalanche\"}[5m])/increase(avalanche_C_db_get_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(avalanche_C_db_delete_sum{job=\"avalanche\"}[5m])/increase(avalanche_C_db_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(avalanche_C_db_has_sum{job=\"avalanche\"}[5m])/increase(avalanche_C_db_has_count{job=\"avalanche\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(avalanche_C_db_compact_size_sum{job=\"avalanche\"}[5m])/increase(avalanche_C_db_compact_size_count{job=\"avalanche\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(avalanche_C_db_batch_put_sum{job=\"avalanche\"}[5m])/increase(avalanche_C_db_batch_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(avalanche_C_db_batch_delete_sum{job=\"avalanche\"}[5m])/increase(avalanche_C_db_batch_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(avalanche_C_db_batch_reset_sum{job=\"avalanche\"}[5m])/increase(avalanche_C_db_batch_reset_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(avalanche_C_db_batch_replay_sum{job=\"avalanche\"}[5m])/increase(avalanche_C_db_batch_replay_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  }
 ]
}
{
 "title": "Avalanche Main Dashboard",
 "description": "Home dashboard with the most important indicators for your node and machine",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime average",
   "type": "gauge",
   "description": "Stake weighted average uptime of your node, as reported by network peers. If this falls below 80% node probably won't be rewarded for the current staking period.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_network_node_uptime_weighted_average{job=\"avalanche\"}"
    }
   ]
  },
  {
   "title": "Rewarding stake",
   "type": "gauge",
   "description": "Percentage of the stake that view your node as sufficiently online and correct to vote that node be awarded at the end of the staking period.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_network_node_uptime_rewarding_stake{job=\"avalanche\"}",
     "legendFormat": "Rewarding stake"
    }
   ]
  },
  {
   "title": "X Chain Vertices",
   "type": "timeseries",
   "description": "Number of accepted and rejected vertices on the X chain in the last minute",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(avalanche_X_vtx_accepted_count{job=\"avalanche\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(avalanche_X_vtx_rejected_count{job=\"avalanche\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "P Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the P chain in the last minute.",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(avalanche_P_blks_accepted_count{job=\"avalanche\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(avalanche_P_blks_rejected_count{job=\"avalanche\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Proposed P blocks",
   "type": "stat",
   "description": "Number of P-Chain blocks this node has proposed on the network in the last day. Since block production on P-Chain is usually below the target rate, every node proposes P blocks.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(avalanche_P_blks_built{job=\"avalanche\"}[1d]))",
     "legendFormat": "Proposed P blocks"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Percentage of CPU used",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"avalanche-machine\", mode=\"idle\"}[1m])) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "description": "Percentage of storage filled",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(((node_filesystem_size_bytes{job=~\"avalanche-machine\", fstype=~\"ext4|vfat\"} - node_filesystem_free_bytes{job=~\"avalanche-machine\", fstype=~\"ext4|vfat\"}) / node_filesystem_size_bytes{job=~\"avalanche-machine\", fstype=~\"ext4|vfat\"}) * 100) by (instance)"
    }
   ]
  },
  {
   "title": "Failing health checks",
   "type": "gauge",
   "description": "Number of currently failing internal health checks",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_health_checks_failing{job=\"avalanche\"}"
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "stat",
   "description": "Average time to get a response from a peer",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_requests_average_latency"
    }
   ]
  },
  {
   "title": "Total staked",
   "type": "stat",
   "description": "Amount of AVAX currently staked",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_P_vm_total_staked{job=\"avalanche\"}/1000000000",
     "legendFormat": "AVAX"
    }
   ]
  },
  {
   "title": "Stake connected",
   "type": "stat",
   "description": "Amount of network stake node is currently connected to",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_P_vm_percent_connected{job=\"avalanche\"}"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "timeseries",
   "description": "Number of peers node is connected to",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_network_peers{job=\"avalanche\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "C Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the C chain in the last minute.",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(avalanche_C_blks_accepted_count{job=\"avalanche\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(avalanche_C_blks_rejected_count{job=\"avalanche\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Proposed C blocks",
   "type": "stat",
   "description": "Number of blocks this node has proposed on the C-Chain in the last day. Since C-Chain blocks are produced at a fast rate, block producers are selected by stake weight.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(avalanche_C_blks_built{job=\"avalanche\"}[1d]))",
     "legendFormat": "Built C blocks"
    }
   ]
  },
  {
   "title": "Accepted Blocks/Vertices",
   "type": "bargauge",
   "description": "Number of blocks/vertices accepted in the last minute",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(avalanche_X_vtx_accepted_count{job=\"avalanche\"}[1m]))",
     "legendFormat": "X Chain"
    },
    {
     "expr": "round(increase(avalanche_P_blks_accepted_count{job=\"avalanche\"}[1m]))",
     "legendFormat": "P Chain"
    },
    {
     "expr": "round(increase(avalanche_C_blks_accepted_count{job=\"avalanche\"}[1m]))",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Processing",
   "type": "bargauge",
   "description": "Number of blocks/vertices currently being processed by the node",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_X_vtx_processing{job=\"avalanche\"}",
     "legendFormat": "X Chain"
    },
    {
     "expr": "avalanche_P_blks_processing{job=\"avalanche\"}",
     "legendFormat": "P Chain"
    },
    {
     "expr": "avalanche_C_blks_processing{job=\"avalanche\"}",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Benched nodes",
   "type": "bargauge",
   "description": "Number of peers currently being benched (ignored) by the node",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_X_benchlist_benched_num{job=\"avalanche\"}",
     "legendFormat": "X Chain"
    },
    {
     "expr": "avalanche_P_benchlist_benched_num{job=\"avalanche\"}",
     "legendFormat": "P Chain"
    },
    {
     "expr": "avalanche_C_benchlist_benched_num{job=\"avalanche\"}",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Queries success",
   "type": "bargauge",
   "description": "Percentage of successful queries per chain in the last minute",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(avalanche_X_handler_chits_count{job=\"avalanche\"}[1m]) + 1) / (increase(avalanche_X_handler_chits_count{job=\"avalanche\"}[1m]) + increase(avalanche_X_handler_query_failed_count{job=\"avalanche\"}[1m]) + 1)",
     "legendFormat": "X Chain"
    },
    {
     "expr": "(increase(avalanche_P_handler_chits_count{job=\"avalanche\"}[1m]) + 1) / (increase(avalanche_P_handler_chits_count{job=\"avalanche\"}[1m]) + increase(avalanche_P_handler_query_failed_count{job=\"avalanche\"}[1m]) + 1)",
     "legendFormat": "P Chain"
    },
    {
     "expr": "(increase(avalanche_C_handler_chits_count{job=\"avalanche\"}[1m]) + 1) / (increase(avalanche_C_handler_chits_count{job=\"avalanche\"}[1m]) + increase(avalanche_C_handler_query_failed_count{job=\"avalanche\"}[1m]) + 1)",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Database Operations Latency",
   "type": "timeseries",
   "description": "How long each database operation is taking on average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_db_put_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(avalanche_db_get_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_get_count{job=\"avalanche\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(avalanche_db_delete_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(avalanche_db_has_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_has_count{job=\"avalanche\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(avalanche_db_compact_size_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_compact_size_count{job=\"avalanche\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(avalanche_db_batch_put_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_batch_put_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(avalanche_db_batch_delete_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_batch_delete_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(avalanche_db_batch_reset_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_batch_reset_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(avalanche_db_batch_replay_sum{job=\"avalanche\"}[5m])/increase(avalanche_db_batch_replay_count{job=\"avalanche\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  }
 ]
}
{
 "title": "Network",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime average",
   "type": "timeseries",
   "description": "Stake weighted average uptime of your node, as reported by network peers. If this falls below 80% node probably won't be rewarded for the current staking period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avalanche_network_node_uptime_weighted_average{job=\"avalanche\"}",
     "legendFormat": "Uptime average"
    }
   ]
  },
  {
   "title": "Rewarding stake",
   "type": "timeseries",
   "description": "Percentage of the stake that view your node as sufficiently online and correct to vote that node be awarded at the end of the staking period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avalanche_network_node_uptime_rewarding_stake{job=\"avalanche\"}",
     "legendFormat": "Rewarding stake"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "timeseries",
   "description": "Number of network peers the node is connected to",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_network_peers{job=\"avalanche\"}",
     "legendFormat": "Peers connected"
    }
   ]
  },
  {
   "title": "Network Timing",
   "type": "timeseries",
   "description": "Shows the amount of time this node will wait for a response to a request before considering the request failed, and the average time it takes to get a response to a request.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avalanche_requests_current_timeout",
     "legendFormat": "Timeout"
    },
    {
     "expr": "avalanche_requests_average_latency",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "timeseries",
   "description": "Number of outstanding requests related to consensus/bootstrapping. Doesn't include handshake messages.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    { "expr": "avalanche_requests_outstanding", "legendFormat": "Outstanding Requests" }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_accepted_received{job=\"avalanche\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_received{job=\"avalanche\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_frontier_received{job=\"avalanche\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(avalanche_network_get_ancestors_received{job=\"avalanche\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_network_put_received{job=\"avalanche\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_network_multi_put_received{job=\"avalanche\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_network_get_version_received{job=\"avalanche\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(avalanche_network_get_peerlist_received{job=\"avalanche\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(avalanche_network_pull_query_received{job=\"avalanche\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_network_push_query_received{job=\"avalanche\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_network_version_received{job=\"avalanche\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(avalanche_network_ping_received{job=\"avalanche\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(avalanche_network_pong_received{job=\"avalanche\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(avalanche_network_get_received{job=\"avalanche\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_network_chits_received{job=\"avalanche\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_network_app_gossip_received{job=\"avalanche\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(avalanche_network_app_request_received{job=\"avalanche\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(avalanche_network_app_response_received{job=\"avalanche\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Messages Sent per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_accepted_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_frontier_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(avalanche_network_get_ancestors_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_network_put_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_network_multi_put_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_network_get_version_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(avalanche_network_get_peerlist_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(avalanche_network_pull_query_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_network_push_query_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_network_version_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(avalanche_network_ping_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(avalanche_network_pong_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(avalanche_network_get_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_network_chits_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_network_app_gossip_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(avalanche_network_app_request_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(avalanche_network_app_response_sent{job=\"avalanche\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Benched stake",
   "type": "timeseries",
   "description": "Amount of the stake in AVAX that is benched (ignored) because the nodes are unhealthy",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_X_benchlist_benched_weight/1000000000",
     "legendFormat": "X chain"
    },
    {
     "expr": "avalanche_P_benchlist_benched_weight/1000000000",
     "legendFormat": "P Chain"
    },
    {
     "expr": "avalanche_C_benchlist_benched_weight/1000000000",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Queries Sent per Accepted Container",
   "type": "timeseries",
   "description": "Considers the X-Chain, P-Chain and C-Chain. A lower value indicates vote pipelining (good.) A higher value indicates failed polls (not good.)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "($A + $B) / ($C + $D + $E)", "type": "math" }
   ]
  },
  {
   "title": "Messages Awaiting Send",
   "type": "timeseries",
   "description": "Number of messages that are queued to be sent to peers",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "avalanche_network_throttler_outbound_awaiting_release",
     "legendFormat": "Messages"
    }
   ]
  },
  { "title": "Inbound Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Inbound Byte Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire bytes from the inbound message throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "avalanche_network_byte_throttler_inbound_awaiting_acquire",
     "legendFormat": "Messages Awaiting Acquire"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Remaining Validator Bytyes",
   "type": "timeseries",
   "description": "Number of bytes left in the validator byte allocation of the inbound message throttler",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_network_byte_throttler_inbound_remaining_validator_bytes",
     "legendFormat": "Bytes Remaining"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Acquire Latency",
   "type": "timeseries",
   "description": "The amount of time, on average, that we wait to acquire bytes from the throttler before reading a message.",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_network_byte_throttler_inbound_acquire_latency_sum[2m])/increase(avalanche_network_byte_throttler_inbound_acquire_latency_count[2m])",
     "legendFormat": "Acquire"
    }
   ]
  },
  {
   "title": "Inbound Buffer Throttler Acquire Latency",
   "type": "timeseries",
   "description": "The amount of time, on average, that we wait to acquire from the throttler before reading a message.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_network_buffer_throttler_inbound_acquire_latency_sum[2m])/increase(avalanche_network_buffer_throttler_inbound_acquire_latency_count[2m])",
     "legendFormat": "Acquire"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Awaiting Release (Messages Processing)",
   "type": "timeseries",
   "description": "Number of messages that are currently being handled and haven't yet returned their bytes to the inbound message throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 42 },
   "targets": [
    {
     "expr": "avalanche_network_byte_throttler_inbound_awaiting_release",
     "legendFormat": "Messages Awaiting Release"
    }
   ]
  },
  {
   "title": "Inbound Buffer Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire from the inbound message buffer throttler.",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 42 },
   "targets": [
    {
     "expr": "avalanche_network_buffer_throttler_inbound_awaiting_acquire",
     "legendFormat": "Messages Awaiting"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Remaining At-Large Bytes",
   "type": "timeseries",
   "description": "Number of bytes left in the at-large byte allocation of the inbound message throttler",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_network_byte_throttler_inbound_remaining_at_large_bytes",
     "legendFormat": "Remaining Bytes"
    }
   ]
  },
  {
   "title": "Inbound Bandwidth Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire bytes from the inbound bandwidth throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 50 },
   "targets": [
    {
     "expr": "avalanche_network_bandwidth_throttler_inbound_awaiting_acquire",
     "legendFormat": "Messages Awaiting Acquire"
    }
   ]
  },
  { "title": "Outbound Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Outbound Throttler Remaining At-Large Bytyes",
   "type": "timeseries",
   "description": "Number of bytes left in the at-large byte allocation of the outbound message throttler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_network_throttler_outbound_remaining_at_large_bytes",
     "legendFormat": "Bytes Remaining"
    }
   ]
  },
  {
   "title": "Outbound Throttler Remaining Validator Bytyes",
   "type": "timeseries",
   "description": "Number of bytes left in the validator byte allocation of the outbound message throttler",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_network_throttler_outbound_remaining_validator_bytes",
     "legendFormat": "Bytes Remaining"
    }
   ]
  },
  { "title": "Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Messages Failed To Send per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_accepted_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_frontier_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(avalanche_network_get_ancestors_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_network_put_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_network_multi_put_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_network_get_version_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(avalanche_network_get_peerlist_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(avalanche_network_pull_query_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_network_push_query_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_network_version_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(avalanche_network_ping_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(avalanche_network_pong_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(avalanche_network_chits_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_network_app_gossip_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(avalanche_network_app_request_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(avalanche_network_app_response_failed{job=\"avalanche\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Messages Failed To Parse per Minute",
   "type": "timeseries",
   "description": "Number of messages that could not be parsed because they were of unknown type or invalidly formatted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "increase(avalanche_network_msgs_failed_to_parse[1m])>0",
     "legendFormat": "Failed to Parse"
    }
   ]
  },
  {
   "title": "Inbound Messages Dropped in Last Minute",
   "type": "timeseries",
   "description": "Number of inbound messages dropped (not processed) due to expiration in last minute.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "increase(avalanche_P_handler_expired[1m])+increase(avalanche_C_handler_expired[1m])+increase(avalanche_X_handler_expired[1m])",
     "legendFormat": "Messages Dropped"
    }
   ]
  },
  {
   "title": "Outbound Messages Dropped in Last Minute",
   "type": "timeseries",
   "description": "Number of outbound messages dropped (not sent) due to rate-limiting in the last minute",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "targets": [
    {
     "expr": "increase(avalanche_network_throttler_outbound_acquire_failures[1m])",
     "legendFormat": "Messages Dropped"
    }
   ]
  },
  {
   "title": "Inbound Connections Dropped due to Rate-Limiting per Minute",
   "type": "timeseries",
   "description": "Number of inbound connections dropped due to inbound connection rate-limiting",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "targets": [
    {
     "expr": "increase(avalanche_network_inbound_conn_throttler_rate_limited[1m])",
     "legendFormat": "Rate-Limited"
    }
   ]
  },
  { "title": "Compression", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Average Message Compression Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(increase(avalanche_network_codec_multi_put_compress_time_sum[5m])+1)/(increase(avalanche_network_codec_multi_put_compress_time_count[5m])+1)",
     "legendFormat": "Multiput"
    },
    {
     "expr": "(increase(avalanche_network_codec_push_query_compress_time_sum[5m])+1)/(increase(avalanche_network_codec_push_query_compress_time_count[5m])+1)",
     "legendFormat": "Push Query"
    },
    {
     "expr": "(increase(avalanche_network_codec_put_compress_time_sum[5m])+1)/(increase(avalanche_network_codec_put_compress_time_count[5m])+1)",
     "legendFormat": "Put"
    },
    {
     "expr": "(increase(avalanche_network_codec_peerlist_compress_time_sum[5m])+1)/(increase(avalanche_network_codec_peerlist_compress_time_count[5m])+1)",
     "legendFormat": "Peer List"
    },
    {
     "expr": "(increase(avalanche_network_codec_app_gossip_compress_time_sum[5m])+1)/(increase(avalanche_network_codec_app_gossip_compress_time_count[5m])+1)",
     "legendFormat": "App Gossip"
    },
    {
     "expr": "(increase(avalanche_network_codec_app_request_compress_time_sum[5m])+1)/(increase(avalanche_network_codec_app_request_compress_time_count[5m])+1)",
     "legendFormat": "App Request"
    },
    {
     "expr": "(increase(avalanche_network_codec_app_response_compress_time_sum[5m])+1)/(increase(avalanche_network_codec_app_response_compress_time_count[5m])+1)",
     "legendFormat": "App Response"
    }
   ]
  },
  {
   "title": "Total Message Compression Time per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_codec_multi_put_compress_time_sum[5m])",
     "legendFormat": "Multiput"
    },
    {
     "expr": "rate(avalanche_network_codec_push_query_compress_time_sum[5m])",
     "legendFormat": "Push Query"
    },
    {
     "expr": "rate(avalanche_network_codec_put_compress_time_sum[5m])",
     "legendFormat": "Put"
    },
    {
     "expr": "rate(avalanche_network_codec_peerlist_compress_time_sum[5m])",
     "legendFormat": "Peer List"
    },
    {
     "expr": "rate(avalanche_network_codec_app_gossip_compress_time_sum[5m])",
     "legendFormat": "App Gossip"
    },
    {
     "expr": "rate(avalanche_network_codec_app_request_compress_time_sum[5m])",
     "legendFormat": "App Request"
    },
    {
     "expr": "rate(avalanche_network_codec_app_response_compress_time_sum[5m])",
     "legendFormat": "App Response"
    }
   ]
  },
  {
   "title": "Bytes Saved by Compression",
   "type": "timeseries",
   "description": "Rate at which we save bytes (don't send/receive them over the network) by compressing messages/receiving compressed messages.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_multi_put_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound Multiput"
    },
    {
     "expr": "rate(avalanche_network_multi_put_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound Multiput"
    },
    {
     "expr": "rate(avalanche_network_put_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound Put"
    },
    {
     "expr": "rate(avalanche_network_put_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound Put"
    },
    {
     "expr": "rate(avalanche_network_push_query_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound Push Query"
    },
    {
     "expr": "rate(avalanche_network_push_query_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound Push Query"
    },
    {
     "expr": "rate(avalanche_network_peerlist_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound Peer List"
    },
    {
     "expr": "rate(avalanche_network_peerlist_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound Peer List"
    },
    {
     "expr": "rate(avalanche_network_app_gossip_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound App Gossip"
    },
    {
     "expr": "rate(avalanche_network_app_gossip_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound App Gossip"
    },
    {
     "expr": "rate(avalanche_network_app_request_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound App Request"
    },
    {
     "expr": "rate(avalanche_network_app_request_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound App Request"
    },
    {
     "expr": "rate(avalanche_network_app_response_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound App Response"
    },
    {
     "expr": "rate(avalanche_network_app_response_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound App Response"
    }
   ]
  }
 ]
}